import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { NextResponse } from "next/server";

import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";

const MAX_FILE_SIZE = 10 * 1024 * 1024;

const ALLOWED_TYPES = new Map([
  ["image/jpeg", ".jpg"],
  ["image/png", ".png"],
  ["image/webp", ".webp"],
  ["image/gif", ".gif"],
  ["image/avif", ".avif"],
]);

const ALLOWED_FOLDERS = new Set([
  "gallery",
  "events",
  "leadership",
  "general",
]);

function getS3Client() {
  const region = process.env.AWS_REGION;
  const accessKeyId = process.env.AWS_ACCESS_KEY_ID;
  const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;

  if (!region || !accessKeyId || !secretAccessKey) {
    throw new Error("AWS S3 configuration is incomplete.");
  }

  return {
    region,
    client: new S3Client({
      region,
      credentials: {
        accessKeyId,
        secretAccessKey,
      },
    }),
  };
}

export async function POST(request: Request) {
  // Keep authentication outside the try/catch so Next.js can
  // handle the redirect generated by requireAdmin().
  const admin = await requireAdmin();

  try {
    const bucket = process.env.AWS_S3_BUCKET;

    if (!bucket) {
      return NextResponse.json(
        { success: false, error: "AWS_S3_BUCKET is not configured." },
        { status: 500 }
      );
    }

    const formData = await request.formData();
    const file = formData.get("file");
    const folderValue = formData.get("folder");
    const altTextValue = formData.get("altText");

    if (!(file instanceof File)) {
      return NextResponse.json(
        { success: false, error: "No image file was provided." },
        { status: 400 }
      );
    }

    if (file.size <= 0) {
      return NextResponse.json(
        { success: false, error: "The uploaded image is empty." },
        { status: 400 }
      );
    }

    if (file.size > MAX_FILE_SIZE) {
      return NextResponse.json(
        { success: false, error: "Image size must be 10 MB or less." },
        { status: 400 }
      );
    }

    const mimeType = file.type.toLowerCase();
    const extension = ALLOWED_TYPES.get(mimeType);

    if (!extension) {
      return NextResponse.json(
        {
          success: false,
          error: "Unsupported image type. Use JPG, PNG, WebP, GIF, or AVIF.",
        },
        { status: 400 }
      );
    }

    const folder =
      typeof folderValue === "string" && ALLOWED_FOLDERS.has(folderValue)
        ? folderValue
        : "general";

    const altText =
      typeof altTextValue === "string"
        ? altTextValue.trim().slice(0, 250) || null
        : null;

    const { client, region } = getS3Client();

    const storageKey =
      `aijr/${folder}/${Date.now()}-${crypto.randomUUID()}${extension}`;

    const publicUrl =
      `https://${bucket}.s3.${region}.amazonaws.com/` +
      storageKey
        .split("/")
        .map(encodeURIComponent)
        .join("/");

    const body = Buffer.from(await file.arrayBuffer());

    await client.send(
      new PutObjectCommand({
        Bucket: bucket,
        Key: storageKey,
        Body: body,
        ContentType: mimeType,
        ContentLength: file.size,
        CacheControl: "public, max-age=31536000, immutable",
      })
    );

    try {
      const media = await prisma.mediaAsset.create({
        data: {
          storageKey,
          publicUrl,
          mediaType: "IMAGE",
          mimeType,
          fileSize: file.size,
          altText,
          createdById: admin.id,
        },
        select: {
          id: true,
          storageKey: true,
          publicUrl: true,
          mediaType: true,
          mimeType: true,
          fileSize: true,
          altText: true,
          createdAt: true,
        },
      });

      return NextResponse.json({
        success: true,
        data: media,
      });
    } catch (databaseError) {
      try {
        await client.send(
          new DeleteObjectCommand({
            Bucket: bucket,
            Key: storageKey,
          })
        );
      } catch (cleanupError) {
        console.error("Failed to clean up S3 object:", cleanupError);
      }

      throw databaseError;
    }
  } catch (error) {
    console.error("AIJR media upload failed:", error);

    return NextResponse.json(
      {
        success: false,
        error:
          error instanceof Error
            ? error.message
            : "Failed to upload image.",
      },
      { status: 500 }
    );
  }
}
